### ISSUE TITLE
Reorganization?

### ISSUE THREAD

**Issue by cjfields** [h3abionet/H3ABionet-SOPs#5]
At the SAB meeting discussion arose about possibly using this repo for all H3ABioNet SOPs, not just those for workflows.  If so, we will need to think about how to reorganize this appropriately to account for SOPs from other projects, such as FAIR, training, RedCap, etc.

**Comment by azzaea** [comment]
Yes- I think it is worthy to think and talk which design features are absolutely necessary to accommodate this. We might change a few lines, or end up with a different Jekyll theme as a result. Besides the SAB comments #1 , I can think of these are important features to have:


- [ ] Table of content
- [ ] SOP authors
- [ ] Help text for common abbreviations/ key words
- [ ] Social sharing
- [ ] Commenting
- [ ] Visible warnings/ notices when referring to common pitfals
- [ ] Easy navigation from any point in the site to any other (whether on the page itself, or on other pages)


My personal preference in terms of looks is a page with:
1. Left/right panel to different sections in the given page in preview now. It should be persistent as I scroll down the page (because any SOP is long, and it is perceivable that one goes up and down different sections- also it makes it easy on the eye I believe)
2. Top panel with links to other contents in the site.


Currently:

1. _The left panel has the article's authors and a manually generated toc(see [RNA SOP here](https://h3abionet.github.io/H3ABionet-SOPs/RNA-Seq/))_. Both components are important I  I think, but it is not at all convenient to have them lumped together. On the other hand, the table to the right disappears when one scrolls down the page, which is annoying (at least to me)
2. _The top panel links to the 4 SOPs for different genomic analysis scenarios_. We could have groups and drop down menus for each category. For example: _Genomic analysis_ to include the current 4 SOPs; _Data governance_ to include SOPs on data sharing, privacy and FAIR principles; and so on.

Does it make sense?

**Comment by lsmainzer** [comment]
as we discussed on the call recently, my personal preference is to prioritize
- maintainability
- readability/navigation
- ability to comment and discuss by community

**Comment by azzaea** [comment]
I'm responding to the first question in this ticket from @cjfields 
> At the SAB meeting discussion arose about possibly using this repo for all H3ABioNet SOPs, not just those for workflows. If so, we will need to think about how to reorganize this appropriately to account for SOPs from other projects, such as FAIR, training, RedCap, etc.

From the last WP meeting Jan 16th, other projects would define and disseminate their projects outputs however they feel most appropriate, and not necessarily through this site (though they are of course welcome to use it if they wish to - the theme provides possibility to add categories to the top heading bar easily and neatly).  

Ideally, will move over the design features in the other messages and close this issue

**Comment by azzaea** [comment]
Relevant comments have been properly moved to issue #10, so officially closing this one
